# Vagrantfile for amaterasu dev station
Vagrant.configure(2) do |config|

  config.vm.box = "bento/centos-7.1"
  config.vm.network "private_network", ip: "192.168.33.17"
  config.vm.hostname = "kafka-node"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end

  config.vm.provision "shell", run: "always" do |s|
    s.path = "provision.sh"
    s.privileged = true 
  end		 
end
